-- AlterTable
ALTER TABLE `services` ADD COLUMN `examFormType` ENUM('GENERAL', 'EYE', 'DENTAL', 'ENT', 'CARDIOLOGY', 'DERMATOLOGY', 'GYNECOLOGY', 'ORTHOPEDIC') NOT NULL DEFAULT 'GENERAL',
    ADD COLUMN `performerType` ENUM('TECHNICIAN', 'DOCTOR') NOT NULL DEFAULT 'TECHNICIAN';
