export const MessageCodes = {
  // Auth
  REGISTER_SUCCESS: 'AUTH.REGISTER.SUCCESS',
  VERIFY_SUCCESS: 'AUTH.VERIFY.SUCCESS',
  LOGIN_SUCCESS: 'AUTH.LOGIN.SUCCESS',
  LOGOUT_SUCCESS: 'AUTH.LOGOUT.SUCCESS',
  REFRESH_SUCCESS: 'AUTH.REFRESH.SUCCESS',
  PROFILE_RETRIEVED: 'AUTH.PROFILE.RETRIEVED',
  EMAIL_ALREADY_EXISTS: 'AUTH.REGISTER.EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'AUTH.LOGIN.INVALID_CREDENTIALS',
  ACCOUNT_NOT_VERIFIED: 'AUTH.LOGIN.NOT_VERIFIED',
  INVALID_OTP: 'AUTH.VERIFY.INVALID_OTP',
  OTP_EXPIRED: 'AUTH.VERIFY.OTP_EXPIRED',
  INVALID_REFRESH_TOKEN: 'AUTH.REFRESH.INVALID_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'AUTH.REFRESH.TOKEN_EXPIRED',

  // Users
  USER_CREATED: 'USER.CREATE.SUCCESS',
  USER_UPDATED: 'USER.UPDATE.SUCCESS',
  USER_DELETED: 'USER.DELETE.SUCCESS',
  USER_RETRIEVED: 'USER.GET.SUCCESS',
  USER_LIST_RETRIEVED: 'USER.LIST.SUCCESS',
  USER_NOT_FOUND: 'USER.NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER.EMAIL.EXISTS',
  USER_PHONE_EXISTS: 'USER.PHONE.EXISTS',

  // Services
  SERVICE_CREATED: 'SERVICE.CREATE.SUCCESS',
  SERVICE_UPDATED: 'SERVICE.UPDATE.SUCCESS',
  SERVICE_DELETED: 'SERVICE.DELETE.SUCCESS',
  SERVICE_RESTORED: 'SERVICE.RESTORE.SUCCESS',
  SERVICE_RETRIEVED: 'SERVICE.GET.SUCCESS',
  SERVICE_LIST_RETRIEVED: 'SERVICE.LIST.SUCCESS',
  SERVICE_STATISTICS_RETRIEVED: 'SERVICE.STATISTICS.SUCCESS',
  SERVICE_NOT_FOUND: 'SERVICE.NOT_FOUND',
  SERVICE_NAME_EXISTS: 'SERVICE.CREATE.NAME_EXISTS',
  SERVICE_HAS_ACTIVE_BOOKINGS: 'SERVICE.DELETE.HAS_ACTIVE_BOOKINGS',

  // Bookings
  BOOKING_CREATED: 'BOOKING.CREATE.SUCCESS',
  BOOKING_UPDATED: 'BOOKING.UPDATE.SUCCESS',
  BOOKING_CANCELLED: 'BOOKING.CANCEL.SUCCESS',
  BOOKING_DELETED: 'BOOKING.DELETE.SUCCESS',
  BOOKING_RETRIEVED: 'BOOKING.GET.SUCCESS',
  BOOKING_LIST_RETRIEVED: 'BOOKING.LIST.SUCCESS',
  BOOKING_NOT_FOUND: 'BOOKING.NOT_FOUND',
  BOOKING_DUPLICATE: 'BOOKING.CREATE.DUPLICATE',
  BOOKING_INVALID_DATE: 'BOOKING.CREATE.INVALID_DATE',
  BOOKING_INVALID_STATUS_TRANSITION: 'BOOKING.UPDATE.INVALID_TRANSITION',

  // Queue
  QUEUE_PROMOTED: 'QUEUE.PROMOTE.SUCCESS',
  QUEUE_RETRIEVED: 'QUEUE.GET.SUCCESS',
  QUEUE_LIST_RETRIEVED: 'QUEUE.LIST.SUCCESS',
  QUEUE_STATISTICS_RETRIEVED: 'QUEUE.STATISTICS.SUCCESS',
  QUEUE_NOT_FOUND: 'QUEUE.NOT_FOUND',
  QUEUE_SLOT_FULL: 'QUEUE.PROMOTE.SLOT_FULL',

  // Suggestions
  SUGGESTIONS_RETRIEVED: 'SUGGESTIONS.GET.SUCCESS',

  // Schedules
  SCHEDULE_CREATED: 'SCHEDULE.CREATE.SUCCESS',
  SCHEDULE_UPDATED: 'SCHEDULE.UPDATE.SUCCESS',
  SCHEDULE_DELETED: 'SCHEDULE.DELETE.SUCCESS',
  SCHEDULE_RETRIEVED: 'SCHEDULE.GET.SUCCESS',
  SCHEDULE_LIST_RETRIEVED: 'SCHEDULE.LIST.SUCCESS',
  SCHEDULE_NOT_FOUND: 'SCHEDULE.NOT_FOUND',
  SCHEDULE_CONFLICT: 'SCHEDULE.CREATE.CONFLICT',
  AVAILABLE_SLOTS_RETRIEVED: 'SCHEDULE.SLOTS.SUCCESS',
} as const;
