export const MessageCodes = {
  // Success codes
  REGISTER_SUCCESS: 'AUTH.REGISTER.SUCCESS',
  LOGIN_SUCCESS: 'AUTH.LOGIN.SUCCESS',
  VERIFY_SUCCESS: 'AUTH.VERIFY.SUCCESS',
  PROFILE_RETRIEVED: 'AUTH.PROFILE.SUCCESS',
  REFRESH_SUCCESS: 'AUTH.REFRESH.SUCCESS',
  LOGOUT_SUCCESS: 'AUTH.LOGOUT.SUCCESS',

  // Error codes
  EMAIL_ALREADY_EXISTS: 'AUTH.REGISTER.EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'AUTH.LOGIN.INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'AUTH.LOGIN.ACCOUNT_INACTIVE',
  ACCOUNT_NOT_VERIFIED: 'AUTH.LOGIN.NOT_VERIFIED',
  USER_NOT_FOUND: 'AUTH.USER.NOT_FOUND',
  INVALID_OTP: 'AUTH.VERIFY.INVALID_OTP',
  OTP_EXPIRED: 'AUTH.VERIFY.OTP_EXPIRED',
  OTP_ALREADY_USED: 'AUTH.VERIFY.OTP_USED',
  INVALID_REFRESH_TOKEN: 'AUTH.REFRESH.INVALID_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'AUTH.REFRESH.TOKEN_EXPIRED',
} as const;
